import { Providers } from "@/contexts/main";
import "./globals.css";

export const metadata = {
  title: "PDF Reader for Rafed company",
  description: "Generated by Next and React js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body className={``}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
