import "./globals.css";
import Providers from "@/app/providers";
import {DataProviders} from "@/contexts/main";

export const metadata = {
    title: "PDF Reader for Rafed company",
    description: "Generated by Next and React js",
};

export default function RootLayout({children}) {
    return (
        <html lang="fa" dir="rtl" suppressHydrationWarning>
        <body className={``}>
        <Providers>
            <DataProviders>
                {children}
            </DataProviders>
        </Providers>
        </body>
        </html>
    );
}
